### PR TITLE
4 modules

### PR DESCRIPTION
**Pull request by MaksymSelenkov**
https://maksymselenkov.github.io/frontend-course-2021/homeworks/maksym.selenkov_MaksymSelenkov/4-modules/index.html

### CODE REVIEW

**Review by DrSmile444 — CHANGES_REQUESTED** [review]
Well done!
The last thing I want to ask is to add the package-lock.json you have deleted. The best case is to have it original, so revert it please.

**Comment by MaksymSelenkov** [comment]
I think "lock" commit added original package-lock.json. Don't it?
https://github.com/MastersAcademy/frontend-course-2021/pull/151/commits/b66a98a03cf7b31e16913155a6d81f763992671d

**Comment by DrSmile444** [comment]
@MaksymSelenkov, suddenly, it removes package-lock.json. It seems like that's why you have conflicts, and we can't merge your homework.

**Review by DrSmile444 — APPROVED** [review]

**Review by DrSmile444 — APPROVED** [review]
Good job!

**Review by DrSmile444 — APPROVED** [review]

**Pull request merged**
